name: Cppcheck

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Cppcheck
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=misra --inline-suppr